import type { Metadata } from "next";
import { Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";


const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  display: 'swap', // Prevents layout shift
  variable: '--font-playfair-display', // Useful for Tailwind
});

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap', // Prevents layout shift
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfairDisplay.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
